### PR TITLE
Hamburger Menu

### PR DESCRIPTION
**Pull request by GreenBeard**
Work in progress.

### CODE REVIEW

**Comment by GreenBeard** [comment]
It should work minus the fact that the minifer is changing the `z-index` to 1.

**Comment by calebeby** [comment]
yup we'll wait till we merge my PR, which should fix the minfier bug

**Comment by GreenBeard** [comment]
@fharding1 Thanks for admin panel check. I was not sure how I should do that. :+1:

**Comment by calebeby** [comment]
Closing this for now since we don't need a menu at this time. We may reopen in the future as we add more pages

**Pull request closed without merging**
