### PR TITLE
Added a starter /event/* page

### PR DESCRIPTION
**Pull request by GreenBeard**
I have a feeling that Caleb is not going to like my changes to so many files...
I apologize in advance.

Anyway, there are two matches artificially added for debugging/viewing purposes. Feel free to remove them when the backend has correctly implemented the endpoint.

Also I styled "<a>" so that it did not look so awful. Hopefully that was alright.

### CODE REVIEW

**Comment by GreenBeard** [comment]
Ehh... I removed the "WIP" since I think it really should be merged and worked on from their. Also sorry Caleb for not using camelCase. I realized that now, if it is a **big** deal I will change it.

**Comment by calebeby** [comment]
Sorry, I already started working on one... https://github.com/Pigmice2733/scouting-frontend/pull/2

**Comment by GreenBeard** [comment]
@calebeby This has more work on it completed. The other does not have much done at all... If it is broken or is not following the planned design, then I could update it to address those issues.

**Comment by calebeby** [comment]
I have more changes locally, I'll push

**Pull request closed without merging**
